apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base
- configmap.yaml

labels:
- pairs:
    environment: dev
  includeSelectors: true

images:
- name: pzajko/cicd-application
  newTag: 0.0.5-dev

replicas:
- name: cicd-application
  count: 1
