apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

labels:
  - pairs:
      - key: app
        value: cicd-application
      - key: env
        value: dev

images:
- name: pzajko/cicd-application
  newTag: 0.0.5-dev

patches:
- patch: |-
    - op: replace
      path: /data/WELCOME_MESSAGE
      value: "Welcome to Development Environment!"
  target:
    kind: ConfigMap
    name: app-config

replicas:
- name: cicd-application
  count: 1 