apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

labels:
  - pairs:
      - key: app
        value: cicd-application
      - key: env
        value: dev