apiVersion: v1
kind: Service
metadata:
  name: cicd-application
spec:
  type: LoadBalancer
  selector:
    app: cicd-application
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080 