apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base
- configmap.yaml

labels:
- pairs:
    environment: prod
  includeSelectors: true

images:
- name: pzajko/cicd-application
  newTag: 0.0.5-prod

replicas:
- name: cicd-application
  count: 2 