apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thepolishdev/cicd-application.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 