apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-application
  labels:
    app: cicd-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-application
  template:
    metadata:
      labels:
        app: cicd-application
    spec:
      containers:
      - name: cicd-application
        image: cicd-application:0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config